### PR TITLE
Create UI: text update for restoration edit business or corporation

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#15173

*Description of changes:*

Screenshot 2023-03-10 at 2 46 54 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by jonathan-longe** [comment]
Nicely done @kzdev420 Can you increment the package version by using:  `npm version patch --no-git-tag-version` and commit the changes?

**Comment by severinbeauvais** [comment]
Kevin, I've added a couple more reviewers. With your first few PRs, it's nice to have at least a couple of reviewers, which can include me, Jonathan, Ketaki and Karim.

Also, if your PR changes some significant stuff that others should know about, adding them as reviewers is a good idea.

**Comment by kzdev420** [comment]
> version

**Review by severinbeauvais — APPROVED** [review]
LGTM

Please wait for at least 2 reviews before merging.

**Review by JazzarKarim — APPROVED** [review]
Looks good to me! 👍

**Review by ketaki-deodhar — COMMENTED** [review]
Looks good

**Review by jonathan-longe — APPROVED** [review]
Nicely done @kzdev420

**Pull request merged**
