### PR TITLE
Fixed-19483-Spelling and Grammar in Address Component

### PR DESCRIPTION
**Pull request by ArwenQin**
*Issue #:* /bcgov/entity#19483

*Description of changes:*
- Updated the sentence in Registered Office Address for Amal/Incorp/ContIn/Resto
- Fix Ticket #19483

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-718-muxggtlx.web.app

**Review by severinbeauvais — APPROVED** [review]
Good collateral fixes.

**Comment by severinbeauvais** [comment]
> * Updated the sentence in Registered Office Address for Amal/Incorp/ContIn/Resto
> * Fix ticket [19483 - Staff Payment Restore #715](https://github.com/bcgov/business-create-ui/pull/715)  (Ticket #19483)

What's this about ticket 19483? I don't see a fix in this PR.

**Comment by ArwenQin** [comment]
> > * Updated the sentence in Registered Office Address for Amal/Incorp/ContIn/Resto
> > * Fix ticket [19483 - Staff Payment Restore #715](https://github.com/bcgov/business-create-ui/pull/715)  (Ticket #19483)
> 
> What's this about ticket 19483? I don't see a fix in this PR.

The ticket number is 19483:
image
It linked to that PR. But seems not related to that PR..

**Comment by severinbeauvais** [comment]
> It linked to that PR. But seems not related to that PR..

I think we can't unlink a PR/ticket, but you should delete it from this PR's description.

**Pull request merged**
