### PR TITLE
Regression Testing Adjustments

### PR DESCRIPTION
**Pull request by cameron-freshworks**
*Issue #:* /bcgov/entity#10097

*Description of changes:*
* Fixed Tooltip styling to make consistent through IA and Dissolutions.
* Fixed Redirect URL for Completed Dissolutions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM.

So this is cleanup / catchup, not display issues, right?

**Review by argush3 — APPROVED** [review]

**Comment by cameron-freshworks** [comment]
> LGTM.
> 
> So this is cleanup / catchup, not display issues, right?

A bit of both, this fixes the tooltip displays in Create UI and cleans up our redirect url to handle both filing types. ( ie temp reg or business id )

**Comment by severinbeauvais** [comment]
> > LGTM.
> > So this is cleanup / catchup, not display issues, right?
> 
> A bit of both, this fixes the tooltip displays in Create UI and cleans up our redirect url to handle both filing types. ( ie temp reg or business id )

Oh right, the breadcrumb link. 👍

**Comment by cameron-freshworks** [comment]
> > > LGTM.
> > > So this is cleanup / catchup, not display issues, right?
> > 
> > 
> > A bit of both, this fixes the tooltip displays in Create UI and cleans up our redirect url to handle both filing types. ( ie temp reg or business id )
> 
> Oh right, the breadcrumb link. 👍

Definitely! We fixed the breadcrumb a bit earlier and here we are utilizing that same computed property to supply the redirect url when filing specifically etc. There was a redundant local getting we were able to remove in this clean up :)

**Pull request merged**
