### PR TITLE
19745 Implemented compatible entity type check for adoptee businesses

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#19745

*Description of changes:*
    - app version = 5.8.14
    - imported updated correct-name shared component
    - now filter adoptee businesses here instead of in shared component
    - added filter for entity type
    - added test suite

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-654-90fblr75.web.app

**Comment by severinbeauvais** [comment]
Before (ie, in Dev):

image

After (ie, localhost):

image

**Comment by severinbeauvais** [comment]
When there are no compatible TING businesses to adopt the name from:

image

**Review by vysakh-menon-aot — APPROVED** [review]

**Review by ketaki-deodhar — APPROVED** [review]

**Pull request merged**
