### PR TITLE
19210 Do not save or restore the numbered name

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#19210

*Description of changes:*
- app version = 5.6.33
- do not save numbered name
- do not restore numbered name

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
### With no option selected:

image

image

### With numbered option selected:

image

image

**Review by vysakh-menon-aot — APPROVED** [review]

**Review by JazzarKarim — APPROVED** [review]
👍

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-619-n17ohxb8.web.app

**Pull request merged**
