### PR TITLE
18788 Added fallback

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#18788

*Description of changes:*
- app version = 5.6.21
- added fallback for drafts created without Correct Name Option

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by JazzarKarim — APPROVED** [review]

**Review by JazzarKarim — APPROVED** [review]

**Comment by severinbeauvais** [comment]
All - do you think I should create tickets to set the initial correctNameOption value in the 3+ places where an amalgamation application is created, or is it better to just keep this fallback here?

**Comment by JazzarKarim** [comment]
> All - do you think I should create tickets to set the initial correctNameOption value in the 3+ places where an amalgamation application is created, or is it better to just keep this fallback here?

I'm OK with keeping the fallback here! 🙏 I'm also good with the other option too.

**Comment by severinbeauvais** [comment]
> > All - do you think I should create tickets to set the initial correctNameOption value in the 3+ places where an amalgamation application is created, or is it better to just keep this fallback here?
> 
> I'm OK with keeping the fallback here! 🙏 I'm also good with the other option too.

Thanks. As for me, on the one hand I dislike "special cases" or "fallbacks" when we could/should be handling something earlier on in the process. On the other hand, I could argue that the business name option is not part of initial draft data (ie, it is part of the application other data). So, I'm not going to overthink this :)

**Review by ketaki-deodhar — APPROVED** [review]
Looks good!

**Pull request merged**
