### PR TITLE
ops-support-3105 More fixes

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#17765

This is a fix for ops-support ticket # 3105.

*Description of changes:*
- app version = 5.4.3
- another fix to previewImageSource()

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-564-af5cyrp4.web.app

**Comment by severinbeauvais** [comment]
Screenshots from temp link above:

image

image

**Review by JazzarKarim — APPROVED** [review]
Looks great. Thank you so much for taking care of this Sev and Travis while I was OOO on Friday 😃

**Comment by JazzarKarim** [comment]
Can I merge this PR please?

cc: @seeker25

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
