### PR TITLE
8913 vd special resolution uxa feedback: date format related updates

### PR DESCRIPTION
**Pull request by argush3**
*Issue #:* /bcgov/entity#8913

*Description of changes:*

* Update to use v1.1.9 of shared component date picker.  This component has been updated to use the desired format of `November 30, 2021` as opposed to `Nov 30, 2021`.
* Update date validation error messaged to also use same date format as date picker display date.
* bumped app version num

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by cameron-freshworks — APPROVED** [review]
Looks good!

**Review by severinbeauvais — APPROVED** [review]
Looks good.

I'm surprised no tests broke. I guess we'll have to add some sometime.

**Comment by argush3** [comment]
> Looks good.
> 
> I'm surprised no tests broke. I guess we'll have to add some sometime.

yeah, particularly around all the date stuff.

**Comment by severinbeauvais** [comment]
I forgot to ask: did you verify the max date string while your PC's clock is between 12:00am and 7:59am (inclusive)?

Curious because `resolutionDateMax` is assigned "new Date()". Internally it's a UTC. `dateToPacificDate()` should convert it correctly but ... curious.

**Pull request merged**
