### PR TITLE
13995 Show Staff Payment section when IA as staff

### PR DESCRIPTION
**Pull request by chenhongjing**
*Issue :* /bcgov/entity#13995

*Description of changes:*

- Show Staff Payment section when IA as staff
- Add unit test

**Before**

image

**After**

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — COMMENTED** [review]
Looks good.

Did you try it locally as staff and non-staff to verify that everything looks as it should, routes as is should, and there are no dev console errors?

**Comment by chenhongjing** [comment]
Just find when I directly visit the review & confirm page, it works as expected for staff and non-staff locally. But when I start IA step by step, it doesn't work. I think I have to double check what is wrong.

**Comment by chenhongjing** [comment]
Solved! I thought when I started IA step by step, it was in local environment. But it redirects to dev actually. Double check it works well as staff and non-staff locally. 😄

**Review by severinbeauvais — APPROVED** [review]
Approved but please wait for another review or 2 before merging.

**Review by JazzarKarim — APPROVED** [review]
LGTM! Great work!

**Review by ketaki-deodhar — APPROVED** [review]
👍 Looks good!

**Pull request merged**
