### PR TITLE
17594 Updates for Node 20

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#17594

*Description of changes:*
- app version = 5.5.0
- updated Dockerfile
- updated CD script
- updated CI script
- updated PR script

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-566-frdavmt2.web.app

**Comment by severinbeauvais** [comment]
I tried this incorporation application. Seems to work without issues!

https://business-create-dev--pr-566-frdavmt2.web.app/incorporation-define-company?id=TLXccJGAlQ&accountid=3040

**Review by JazzarKarim — APPROVED** [review]
I've tested a dissolution (https://business-create-dev--pr-566-frdavmt2.web.app/dissolution-affidavit?id=CP1002553&accountid=3040), looks great Sev! 👍

**Review by ketaki-deodhar — APPROVED** [review]
Looks Good! I played around a bit and filed a Consent to Continue Out. Worked as expected 👍

**Pull request merged**
