### PR TITLE
Added validation for number of shares = 0

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* /bcgov/entity#7505

*Description of changes:*
- added rule for required number of shares
- added rule for number of shares > 0
- added unit tests
- updated app version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
This implementation is similar to the one in bcrs-shared-components but not identical, so I applied the same fix here.

In the future, we should update this UI to use the shared component... I will create a new ticket.

**Review by cameron-freshworks — APPROVED** [review]
✅ ✅ ✅ ✅ ✅ ✅ ✅

**Comment by cameron-freshworks** [comment]
> This implementation is similar to the one in bcrs-shared-components but not identical, so I applied the same fix here.
> 
> In the future, we should update this UI to use the shared component... I will create a new ticket.

I believe there is a ticket to import the shared component already, will most likely come in with the new Create Filings?

**Comment by severinbeauvais** [comment]
> I believe there is a ticket to import the shared component already, will most likely come in with the new Create Filings?

Yup, thanks for the hint. I found:

https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/7397

**Pull request merged**
