### PR TITLE
21110 Deleted documents that were cleared by user

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#21110

**This is part 1 of the ticket (when user clears an uploaded file). Part 2 will be in a separate PR. Unfortunately this isn't testable at the moment because the Legal API endpoint doesn't exist, but it can be verified that this code change doesn't break anything. I will test when I work on part 2.**

*Description of changes:*
- app version = 5.10.24
- added document deletion to Continuation Authorization
- added document deletion to Upload Affidavit
- added document deletion to Complete Affidavit
- added document deletion to Upload Memorandum
- added document deletion to Upload Rules
- added deleteDocument() method

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-707-jgs4u8b5.web.app

**Comment by severinbeauvais** [comment]
This is what happens if you clear (click X) on an uploaded files. Note that is not a CORS error -- it's the Legal API not handling this call. There is no indication to the user that this didn't work (they won't care anyway). Only this console error:

image

**Review by vysakh-menon-aot — APPROVED** [review]

**Review by JazzarKarim — APPROVED** [review]
LGTM

**Pull request merged**
