### PR TITLE
20196 Added some fallbacks to prevent invalid JSON

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#20196

*Description of changes:*
- app version = 5.9.9
- cleaned up some code
- added fallback (to empty string) for business email to all  filings
- added fallback (to empty string) for business phone to all filings
- don't initialize isBusinessLookup when fetching directors (ie, leave it undefined)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-666-q0tfjm9b.web.app

**Review by jamespaologarcia — APPROVED** [review]
LGTM

**Review by PaulGarewal — APPROVED** [review]
Looks good!

**Pull request merged**
