### PR TITLE
21638 Don't save authorization object if it's null/undefined

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#21638

*Description of changes:*
- app version = 5.10.23
- don't save authorization object if it's null/undefined

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
Now saves and reloads correctly:

image

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-704-fpvh1ciy.web.app

**Review by ketaki-deodhar — APPROVED** [review]
Tried by creating a new application and it works 👍

**Pull request merged**
