### PR TITLE
19109 Fixed section title

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#19109

*Description of changes:*
- app version = 5.6.23
- fixed amalgamation information title

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

Screenshot:
image

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-610-rf9tst01.web.app

**Review by leodube-aot — APPROVED** [review]

**Review by JazzarKarim — APPROVED** [review]
I also had this fix in my upcoming PR, you read my mind haha. Found it while writing unit tests 😆

**Comment by severinbeauvais** [comment]
> I also had this fix in my upcoming PR, you read my mind haha. Found it while writing unit tests 😆

Janis mentioned it to me. I'd like to merge this fix here and now so the original ticket can be QAed without issue.

**Pull request merged**
