### PR TITLE
12444 Verify - Create UI SP/GP changes

### PR DESCRIPTION
**Pull request by lewischenstudio**
*Issue #:* /bcgov/entity#12444

*Description of changes:*
- updated texts
- updated unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by lewischenstudio** [comment]
@severinbeauvais Can you take a look at the error in testing-coverage? I'm not sure how to fix the error.

**Review by lambert-alex — APPROVED** [review]
LGTM

**Review by severinbeauvais — APPROVED** [review]
LGTM.

Do we have (or need) a ticket for similar changes to Edit UI?

**Comment by severinbeauvais** [comment]
Also, please update the ticket's state pipeline and tag it to the next release.

**Comment by lewischenstudio** [comment]
> LGTM.
> 
> Do we have (or need) a ticket for similar changes to Edit UI?

The design in Edit UI is different from the Create UI. I don't think we have to unless it is requested by the design team.

**Comment by severinbeauvais** [comment]
> @severinbeauvais Can you take a look at the error in testing-coverage? I'm not sure how to fix the error.

Do you have a link? All checks passed apparently.

**Comment by lewischenstudio** [comment]
> > @severinbeauvais Can you take a look at the error in testing-coverage? I'm not sure how to fix the error.
> 
> Do you have a link? All checks passed apparently.

A moment ago Upload coverage to Codev failed. I re-ran it, and it failed again. Now it's passed. Maybe it's the GH server issue 🤷 It's all good now.

**Comment by lambert-alex** [comment]
> > @severinbeauvais Can you take a look at the error in testing-coverage? I'm not sure how to fix the error.
> 
> Do you have a link? All checks passed apparently.

It was a problem with the testing-coverage build it didn't connect properly. I re ran the job and it works now

**Comment by lewischenstudio** [comment]
> > > @severinbeauvais Can you take a look at the error in testing-coverage? I'm not sure how to fix the error.
> > 
> > 
> > Do you have a link? All checks passed apparently.
> 
> It was a problem with the testing-coverage build it didn't connect properly. I re ran the job and it works now

Nice. Thanks 👍

**Pull request merged**
