### PR TITLE
15930 + 16175 Pinia upgrade and package updates/cleanup

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* bcgov/entity#15930 and bcgov/entity#16175

*Description of changes:*
- merging pinia-upgrade branch into main branch
- see [PR 540](https://github.com/bcgov/business-create-ui/pull/540) and [PR 541](https://github.com/bcgov/business-create-ui/pull/544) for more details

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-create-dev--pr-544-aifmetrd.web.app

**Comment by severinbeauvais** [comment]
Ketaki, Karim, Argus, Hongjing, Vysakh, Chris -- you don't need to review this, but I wanted you to see the process...

1. This is a feature branch to which 2 of us submitted PRs. This allowed us to commit code that would break the branch, but it wasn't main branch so it didn't get auto-deployed to Dev. We may need to commit some small fixes to the feature branch, and I think they will automatically show up in this PR.

2. When I ran `/gcbrun` above, a new GitHub action (check) was run to deploy this to a temporary URL. This allows us to test the code in a deployed environment (not locally). Since this is Create UI code, an example URL is:
`https://business-create-dev--pr-544-aifmetrd.web.app/registration-define-business?id=TEFUWP93U7&accountid=2288`

3. When Ketaki and I are satisfied with our testing on this temporary URL, I will merge this feature branch into main branch, where it will be auto-deployed to Dev and eventually make its way to Test and then Prod.

Let me know if you have any questions.

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-create-dev--pr-544-aifmetrd.web.app

**Comment by severinbeauvais** [comment]
> 2. When I ran `/(deleted)` above, a new GitHub action...

And I just realized that having the command in my comment above kicked off the GH action again, haha. So now we know :)

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-create-dev--pr-544-aifmetrd.web.app

**Pull request merged**
