### PR TITLE
24104 - Hide Fee Summary for Continuation Authorization

### PR DESCRIPTION
**Pull request by ArwenQin**
*Issue #:* /bcgov/entity#24104

*Description of changes:*
- Hide the Fee Summary for Continuation Authorization

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-759-q89jzfwo.web.app

**Comment by ArwenQin** [comment]
I'm confused why it shows $0 for staff, but $350 for regular user.
This is the header and response when it's staff (to Pay API):
image

image


This is the header and response when it's  regular user:
image


image


Both params are the same and both have waiveFees=true. But the response is different.
For now, we hide the fee summary for continuation authorization.

**Comment by ArwenQin** [comment]
see:
https://business-create-dev--pr-759-q89jzfwo.web.app/continuation-in-authorization?id=TXXGAyWSS7&accountid=668

Hide fee:
image

**Review by severinbeauvais — COMMENTED** [review]
LGTM but don't merge until change is approved by Janis or Olga.

**Review by severinbeauvais — COMMENTED** [review]
If it's decided that it's OK to hide the Fee Summary then please update App.vue line 486 (not needed).

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-create-dev--pr-759-q89jzfwo.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by severinbeauvais** [comment]
PS Did you catch Mihai's alternate solution? It was to create a zero-fee entry in the Pay db (using Pay Admin UI). Then we could use that fee code and override the payment text (done elsewhere already). However, Janis and Olga prefer the "hide" option, so that's what we're going with.

**Pull request merged**
